<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Apotek_model extends CI_Model
{

    public $table = 'apotek';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama,no_hp,jalan,provinsi,kota,no_rek,no_izin,apoteker,id_login');
        $this->datatables->from('apotek');
        //add this line for join
        //$this->datatables->join('table2', 'apotek.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('apotek/update/$1'),'<i class="fa fa-pencil"></i>','class="btn btn-info"')." | ".anchor(site_url('apotek/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-danger"','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_by_id_login($id)
    {
        $this->db->where('id_login', $id);
        return $this->db->get($this->table)->row();
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_rek', $q);
	$this->db->or_like('no_izin', $q);
	$this->db->or_like('apoteker', $q);
	$this->db->or_like('id_login', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('no_rek', $q);
	$this->db->or_like('no_izin', $q);
	$this->db->or_like('apoteker', $q);
	$this->db->or_like('id_login', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Apotek_model.php */
/* Location: ./application/models/Apotek_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-14 15:02:13 */
/* http://harviacode.com */