<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bukti_pembayaran_model extends CI_Model
{

    public $table = 'bukti_pembayaran';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,pengirim,penerima,foto,tgl_upload,id_transaksi');
        $this->datatables->from('bukti_pembayaran');
        //add this line for join
        //$this->datatables->join('table2', 'bukti_pembayaran.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('bukti_pembayaran/update/$1'),'<i class="fa fa-pencil"></i>','class="btn btn-info"')." | ".anchor(site_url('bukti_pembayaran/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-danger"','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('tgl_upload', $q);
	$this->db->or_like('id_transaksi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->or_like('penerima', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('tgl_upload', $q);
	$this->db->or_like('id_transaksi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bukti_pembayaran_model.php */
/* Location: ./application/models/Bukti_pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-14 15:02:13 */
/* http://harviacode.com */