<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_obat_model extends CI_Model
{

    public $table = 'jenis_obat';
    public $id = 'jenis_obat.id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama');
        $this->datatables->from('jenis_obat');
        //add this line for join
        //$this->datatables->join('table2', 'jenis_obat.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jenis_obat/update/$1'),'<i class="fa fa-pencil"></i>','class="btn btn-info"')." | ".anchor(site_url('jenis_obat/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-danger"','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_by_produk()
    {

        $this->db->select('jenis_obat.id,jenis_obat.nama');
        $this->db->where('produk.stok >','0');
        $this->db->distinct();
        $this->db->join('produk','produk.id_jenis = jenis_obat.id');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jenis_obat_model.php */
/* Location: ./application/models/Jenis_obat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-24 17:01:52 */
/* http://harviacode.com */