<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_model extends CI_Model
{

    public $table = 'produk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama,komposisi,indikasi,isi,harga,gambar,stok,berat,id_jenis,id_apotek');
        $this->datatables->from('produk');
        //add this line for join
        //$this->datatables->join('table2', 'produk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('produk/update/$1'),'<i class="fa fa-pencil"></i>','class="btn btn-info"')." | ".anchor(site_url('produk/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-danger"','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->where('stok >','0');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_categori($id)
    {
        $this->db->where('stok >','0');
        $this->db->where('id_jenis',$id);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    public function record_count() {
        return $this->db->count_all($this->table);
    }
    public function fetch_data($limit, $id) {
        $this->db->limit($limit);
        $this->db->where($this->id, $id);
        $query = $this->db->get($this->table);
        if ($query->num_rows() > 0) {
            foreach ($query->result() as $row) {
                $data[] = $row;
            }
            return $data;
        }
        return false;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('komposisi', $q);
	$this->db->or_like('indikasi', $q);
	$this->db->or_like('isi', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('berat', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('id_apotek', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('komposisi', $q);
	$this->db->or_like('indikasi', $q);
	$this->db->or_like('isi', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('berat', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('id_apotek', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-24 16:26:15 */
/* http://harviacode.com */